# Generated by Django 2.1.4 on 2019-01-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IForm',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Form', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatediform_iform', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='iform.IForm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatediform_iform', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iform',
            },
        ),
        migrations.CreateModel(
            name='IFormTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('read_only', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('width', models.IntegerField(default=0)),
                ('iform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag', to='iform.IForm')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag_tag', to='tag.Tag')),
            ],
            options={
                'db_table': 'iform_tag',
            },
        ),
        migrations.AlterUniqueTogether(
            name='iformtag',
            unique_together={('iform', 'tag')},
        ),
    ]
