# Generated by Django 3.0.5 on 2021-01-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iform',
            name='collapsible',
            field=models.IntegerField(choices=[('Fixed', 0), ('Default Opened', 1), ('Default Closed', 2)], default=0),
        ),
        migrations.AddField(
            model_name='iform',
            name='layout',
            field=models.IntegerField(choices=[('Normal', 0), ('Inline', 1)], default=0),
        ),
    ]
