# Generated by Django 3.0.5 on 2021-01-24 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iform', '0002_auto_20210121_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='iform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iformtag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatediform_iformtag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iformtag',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iformtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iformtag',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatediform_iformtag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iformtag',
            name='updated_when',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='iform',
            name='collapsible',
            field=models.IntegerField(choices=[(0, 'Fixed'), (1, 'Default Opened'), (2, 'Default Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='iform',
            name='layout',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Inline')], default=0),
        ),
    ]
