# Generated by Django 2.1.5 on 2019-02-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0002_remove_iformtag_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='iform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iforms', to='iform.IForm'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tags', to='tag.Tag'),
        ),
    ]
