# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0005_auto_20170520_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iform',
            name='tag',
        ),
        migrations.AddField(
            model_name='iform',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iform.IForm'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='iform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag', to='iform.IForm'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag', to='tag.Tag'),
        ),
    ]
