# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0007_auto_20170524_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='iform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='iform.IForm'),
        ),
    ]
