# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0011_auto_20170528_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iform',
            name='name',
            field=models.CharField(default='New Form', max_length=255),
        ),
    ]
