# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0015_iformtag_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iformtag',
            name='default_value',
        ),
    ]
