# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0016_remove_iformtag_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='iformtag',
            name='default_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='iformtag',
            name='required',
            field=models.IntegerField(choices=[(1, b'Yes'), (0, b'No')], default=1, verbose_name=b'Required'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag_tag', to='tag.Tag'),
        ),
    ]
