# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0017_auto_20171220_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
