# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0018_auto_20171220_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='iformtag',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
