# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0022_auto_20180111_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
