# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0023_auto_20180111_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iform',
            old_name='date_created',
            new_name='created_when',
        ),
        migrations.RenameField(
            model_name='iform',
            old_name='date_updated',
            new_name='updated_when',
        ),
    ]
