# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0028_auto_20180309_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iform',
            name='level',
        ),
        migrations.RemoveField(
            model_name='iform',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='iform',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='iform',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='iform',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='iform.IForm'),
        ),

    ]
