# Generated by Django 3.0.5 on 2021-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
