# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_when', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Text'), (2, 'Integer Number'), (3, 'Float Point Number'), (4, 'Reference'), (5, 'Yes/No'), (6, 'Date'), (7, 'Time'), (8, 'Date and Time')], null=True, verbose_name='Field Type')),
                ('unit', models.IntegerField(blank=True, choices=[(1, '°C'), (2, 'Kg'), (3, 'm'), (4, 's')], null=True, verbose_name='Unit')),
                ('decimal_places', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('required', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Required')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
