# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='choices_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='default_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, b'Text'), (2, b'Integer Number'), (3, b'Float Point Number'), (4, b'Choices'), (5, b'Yes/No'), (6, b'Date'), (7, b'Time'), (8, b'Date and Time')], null=True, verbose_name=b'Field Type'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, b'\xc2\xb0C'), (2, b'Kg'), (3, b'm'), (4, b's')], null=True, verbose_name=b'Unit'),
        ),
    ]
