# Generated by Django 2.1.4 on 2019-01-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.AddField(
            model_name='tag',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_folder', to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Text'), (2, 'Integer Number'), (3, 'Float Point Number'), (4, 'Choices'), (5, 'Yes/No'), (6, 'Date'), (7, 'Time'), (8, 'Date and Time'), (10, 'File'), (11, 'Section'), (12, 'Text Area'), (13, 'Radio Button'), (14, 'Folder')], null=True, verbose_name='Field Type'),
        ),
    ]
