# Generated by Django 2.1.5 on 2019-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20190103_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='folder',
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Text'), (2, 'Integer Number'), (3, 'Float Point Number'), (4, 'Choices'), (5, 'Yes/No'), (6, 'Date'), (7, 'Time'), (8, 'Date and Time'), (10, 'File'), (11, 'Section'), (12, 'Text Area'), (13, 'Radio Button')], null=True, verbose_name='Field Type'),
        ),
    ]
