# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_tag_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='help',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Help Text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, b'Text'), (2, b'Integer Number'), (3, b'Float Point Number'), (4, b'Choices'), (5, b'Yes/No'), (6, b'Date'), (7, b'Time'), (8, b'Date and Time'), (9, b'Money'), (10, b'File')], null=True, verbose_name=b'Field Type'),
        ),
    ]
