# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_auto_20171225_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='help',
            new_name='help_text',
        ),
    ]
