# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0007_auto_20171230_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, b'Text'), (2, b'Integer Number'), (3, b'Float Point Number'), (4, b'Choices'), (5, b'Yes/No'), (6, b'Date'), (7, b'Time'), (8, b'Date and Time'), (10, b'File'), (11, b'Section'), (12, b'Large Text'), (13, b'Radio Button')], null=True, verbose_name=b'Field Type'),
        ),
    ]
