# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 08:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0011_auto_20180111_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tag.Tag'),
        ),
    ]
