# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0012_auto_20180111_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='date_created',
            new_name='created_when',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='date_updated',
            new_name='updated_when',
        ),
    ]
