# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 11:01
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0015_auto_20180310_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
