# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='created_when',
        ),
        migrations.AddField(
            model_name='value',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
