# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0002_auto_20170519_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='iform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_by_tag', to='iform.IForm'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_by_iform', to='tag.Tag'),
        ),
        migrations.AlterModelTable(
            name='iformtag',
            table='iform_tag',
        ),
    ]
