# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0004_auto_20170520_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
