# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0006_auto_20170522_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iform',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iform.IForm'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tag.Tag'),
        ),
    ]
