# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('iform', '0008_auto_20170524_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iformtag',
            name='iform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag', to='iform.IForm'),
        ),
        migrations.AlterField(
            model_name='iformtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iform_tag', to='tag.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='iformtag',
            unique_together=set([('iform', 'tag')]),
        ),
        migrations.AlterModelTable(
            name='iformtag',
            table=None,
        ),
    ]
