# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0012_auto_20170617_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iform',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='iform',
            name='created_when',
        ),
    ]
