# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 21:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iform', '0013_auto_20170617_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='iform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iform',
            name='created_when',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
