# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iform', '0014_auto_20170617_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='iformtag',
            name='default_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
